# Generated by Django 2.2.16 on 2022-10-10 08:45

import django.core.validators
from django.db import migrations, models
import titles.models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(default=2022, validators=[titles.models.max_value_current_year, django.core.validators.MinValueValidator(1900)], verbose_name='Год выпуска'),
        ),
    ]
