# Generated by Django 2.2.16 on 2022-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20221010_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.SlugField(),
        ),
    ]
