# Generated by Django 2.2.16 on 2022-10-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20221011_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
