# Generated by Django 2.2.16 on 2022-10-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20221013_1140'),
        ('titles', '0002_auto_20221014_1119'),
    ]

    operations = [
    ]
