# Generated by Django 2.2.16 on 2022-10-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_merge_20221014_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
